name = "datahutang"
main = "worker.js"
account_id = "7431e1cb1076e540960f6796b8971a49"
workers_dev = true
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "HUTANG_KV", id = "8f1f653045574e5bae3b0ef0aca0d7b0" }
]

[assets]
binding = "ASSETS"
directory = "public"
